%This code compiles the mex BAceres
%This code assumes that ceres library: http://ceres-solver.org/
%is already installed on the computer.
%In addition, it is assumed that this folder contains the files ceres.lib and glog.lib (the compiled libraries)

%Change to the pathes in your computer
pathCeres='C:\Users\ykasten\Documents\ceresWorking_10_2_2019\ceres-solver-1.14.0.tar/';
pathglog='C:\Users\ykasten\Documents\ceresWorking_10_2_2019\glog-masterb';


mex('-largeArrayDims', ['-I' pathCeres '\'],...
    ['-I' pathCeres '\ceres-solver\include'],...
    ['-I' pathCeres '\ceres-solver\internal'],...
    ['-I' pathCeres '\ceres-solver\internal\ceres'],...
    ['-I' pathCeres '\ceres-solverb\config'],...
    ['-I' pathglog ] ,...
    ['-I' pathglog '\src'], ...
    ['-I' pathglog 'src\windows'], ... 
    'BAceres.cpp','ceres.lib','glog.lib')